# Generated by Django 3.1.7 on 2022-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('slots', models.IntegerField(default=0)),
                ('taken_slots', models.IntegerField(default=0)),
                ('requirements', models.CharField(default='None', max_length=200)),
                ('recurring', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Every Other Day'), (3, 'Weekly'), (4, 'Never'), (5, 'Other...')])),
                ('non_member_cost', models.IntegerField(default=0)),
                ('member_cost', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('amount_due', models.IntegerField(default=0)),
                ('membership_status', models.PositiveSmallIntegerField(choices=[(1, 'NonMember'), (2, 'Member')])),
            ],
        ),
    ]
