# Generated by Django 3.1.7 on 2022-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymca', '0003_auto_20220406_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurring',
            field=models.CharField(max_length=300),
        ),
    ]
